const components = [
  { name: "DrodAccordion", url: "accordion" },
  { name: "DrodAnimatedGradient", url: "animated-gradient" },
  { name: "DrodBackgroundImage", url: "background-image" },
  { name: "DrodBadge", url: "badge" },
  { name: "DrodButton", url: "button" },
  { name: "DrodButtonFloating", url: "button-floating" },
  { name: "DrodButtonGroup", url: "button-group" },
  { name: "DrodCards", url: "cards" },
  { name: "DrodCarousel", url: "carousel" },
  { name: "DrodCarouselSlider", url: "carousel-slider" },
  { name: "DrodCheckbox", url: "checkbox" },
  { name: "DrodDropdown", url: "dropdown" },
  { name: "DrodFallbackPage", url: "fallback-page" },
  { name: "DrodFloatingMenu", url: "floating-menu" },
  { name: "DrodIcon", url: "icon" },
  { name: "DrodIframe", url: "iframe" },
  { name: "DrodInput", url: "input" },
  { name: "DrodInputPassword", url: "input-password" },
  { name: "DrodLink", url: "link" },
  { name: "DrodLoading", url: "loading" },
  { name: "DrodMap", url: "map" },
  { name: "DrodMarkdown", url: "markdown" },
  { name: "DrodMarkdownViewer", url: "markdown-viewer" },
  { name: "DrodMenuActions", url: "MenuActions" },
  { name: "DrodMenuDropdown", url: "MenuDropdown" },
  { name: "DrodMenuIcon", url: "MenuIcon" },
  // { name: "DrodMindmap", url: "mindmap" },
  // { name: "DrodMindmapEditor", url: "mindmap-editor" },
  // { name: "DrodMindmapViewer", url: "mindmap-viewer" },
  { name: "DrodModalBase", url: "ModalBase" },
  { name: "DrodModalDelete", url: "ModalDelete" },
  { name: "DrodModalInfo", url: "ModalInfo" },
  { name: "DrodMultiselect", url: "multiselect" },
  { name: "DrodMusicPlayer", url: "MusicPlayer" },
  { name: "DrodNoData", url: "NoData" },
  { name: "DrodNotification", url: "Notification" },
  { name: "DrodPortrait", url: "portrait" },
  { name: "DrodProgressGroup", url: "progress-group" },
  { name: "DrodReloadPWA", url: "ReloadPWA" },
  { name: "DrodRotateText", url: "RotateText" },
  { name: "DrodSidebar", url: "sidebar" },
  { name: "DrodSwitch", url: "switch" },
  { name: "DrodStackGrid", url: "StackGrid" },
  { name: "DrodTabs", url: "tabs" },
  { name: "DrodTable", url: "table" },
  { name: "DrodTextGlow", url: "TextGlow" },
  { name: "DrodTextGradient", url: "TextGradient" },
  { name: "DrodTimelineVertical", url: "TimelineVertical" },
  { name: "DrodThemeSwitcher", url: "theme-switcher" },
  { name: "DrodTooltip", url: "tooltip" },
  { name: "DrodVerticalSpacing", url: "vertical-spacing" },
  { name: "DrodVideo", url: "video" },
  { name: "DrodVideoGif", url: "gif-player" },
  { name: "DrodVideoScrubbable", url: "video-scrubbable" },
  { name: "DrodVideoSplitter", url: "video-splitter" },
  { name: "DrodYoutube", url: "video-youtube" },
  { name: "DrodWYSIWYViewer", url: "wysiwyg" },
  { name: "DrodWYSIWYViewerEditor", url: "wysiwyg-editor" },
  { name: "DrodWYSIWYViewerViewer", url: "wysiwyg-viewer" },
];

export default components;
